shinyUI(
  
  fluidPage(theme = shinytheme("united"),
            #shinythemes::themeSelector(),
            useShinyjs(),
            titlePanel("Fire Danger Outlook Graphs", windowTitle = "Shiny App"),
            
            navbarPage("",
              
        
              
              tabPanel("Overview of Dataset",
                      # h3("Dataset"),
                       tabsetPanel(
                         navbarMenu("Summary",
                         tabPanel("Summary1",
                                  withSpinner(
                                  verbatimTextOutput(outputId = "SummaryA1"), type = 5, color = "#FFA500", size = 1)
                         ),
                         tabPanel("Summary2",
                                  withSpinner(
                                  verbatimTextOutput(outputId = "SummaryA2"), type = 5, color = "#FFA500", size = 1)
                         )),
                         tabPanel("Raw Data",
                                  withSpinner(
                                  DT::dataTableOutput(outputId = "Assign1"), type = 5, color = "#FFA500", size = 1)
                         )
                       )
              ),
              
              # tabPanel("try",
              #          headerPanel("Dynamic number of plots"),
              #          
              #          sidebarPanel(
              #            sliderInput("n", "Number of plots", value=1, min=1, max=5)
              #          ),
              #          
              #          #mainPanel(
              #            # This is the dynamic UI for the plots
              #            #uiOutput("plots")
              #          #)
              #          ),
              
              tabPanel("Visualisation",
                       #h3("Plots"),
                       
                       tabsetPanel(
                         
                         
                         tabPanel("Station Plots",
                                  br(),
                                  #tabsetPanel(
                                  #tabPanel("STATIONS",
                                  # selectInput(inputId = "region", label ="Region:", choices = list("North_Island" = "North_Island",
                                  #                                                                  "South_Island" = "South_Island",
                                  #                                                                  "unknown_island" = "unknown_island",
                                  # ), selected = "South_island"),
                                  sliderInput(inputId = "comp", label = "Select Year", min = 1970, max = 2019, value = 2007),
                                  
                                  selectInput(inputId = "indexx", label ="Index:", choices = list("BUI" = "BUI",
                                                                                                  "CDSR" = "CDSR",
                                                                                                  "DC" = "DC"
                                  ), selected = "BUI"),
                                  # selectInput(inputId = "region1", label ="Index:", choices = list("Auckland" = "Auckland",
                                  #                                                                 "Bay of Plenty" = "Bay of Plenty",
                                  #                                                                 "Central NI" = "Central NI",
                                  #                                                                 "Chatham Island" ="Chatham Island" ,
                                  #                                                                 "Gisborne"="Gisborne",
                                  #                                                                 "Hawkes Bay"="Hawkes Bay",
                                  #                                                                 "Northland"="Northland",
                                  #                                                                 "Taranaki"= "Taranaki",
                                  #                                                                 "Waikato"="Waikato",
                                  #                                                                 "Wairarapa" ="Wairarapa" ,
                                  #                                                                 "Wanganui-Manawatu"="Wanganui-Manawatu",
                                  #                                                                 "Wellington"= "Wellington",
                                  #                                                                 "Canterbury" ="Canterbury" ,
                                  #                                                                 "Marlborough" = "Marlborough" ,
                                  #                                                                 "Mid-South Canterbury"= "Mid-South Canterbury",
                                  #                                                                 "Nelson"= "Nelson",
                                  #                                                                 "Otago"="Otago",
                                  #                                                                 "Southland"="Southland",
                                  #                                                                 "West Coast" ="West Coast" ,
                                  #                                                                 "unknown region"  = "unknown region"
                                  # 
                                  # 
                                  # 
                                  # 
                                  # 
                                  # 
                                  # ), selected = "Auckland"),
                                  
                                  selectInput(inputId = "station", label ="Stations:", choices = list("Great Barrier Island Raws"   = "Great Barrier Island Raws"  ,  
                                                                                                     "Kaipara Raws" = "Kaipara Raws",            
                                                                                                     "Mahurangi Forest Raws" = "Mahurangi Forest Raws",        
                                                                                                     "Woodhill Raws"     = "Woodhill Raws",            
                                                                                                     "Clevedon Coast Raws" = "Clevedon Coast Raws",           
                                                                                                     "Cornwallis Depot Raws" = "Cornwallis Depot Raws",       
                                                                                                     "Patumahoe Raws"     = "Patumahoe Raws" ,          
                                                                                                     "Waharau Raws"="Waharau Raws" ,                
                                                                                                     "Minden Raws"="Minden Raws"   ,               
                                                                                                     "Opotiki Raws"="Opotiki Raws" ,                 
                                                                                                     "Rotoehu Raws"="Rotoehu Raws" ,                 
                                                                                                     "Tauranga Aero SYNOP "="Tauranga Aero SYNOP ",         
                                                                                                     "Tauranga Raws"="Tauranga Raws",                 
                                                                                                     "Te Puke Ews"="Te Puke Ews"  ,                 
                                                                                                     "TECT All Terrain Park Raws"="TECT All Terrain Park Raws"  ,
                                                                                                     "Waihau Bay Raws"   = "Waihau Bay Raws",        
                                                                                                     "Waihi Beach Raws" = "Waihi Beach Raws",             
                                                                                                     "Whakatane Aero Aws" = "Whakatane Aero Aws"  ,          
                                                                                                     "Whakatane Raws" = "Whakatane Raws",              
                                                                                                     "Galatea Raws" = "Galatea Raws" ,               
                                                                                                     "Kawerau Raws"=  "Kawerau Raws",              
                                                                                                     "Rotorua Aero Aws"   = "Rotorua Aero Aws",          
                                                                                                     "Rotorua Raws"="Rotorua Raws",                  
                                                                                                     "Waimana Raws"="Rotorua Raws",                 
                                                                                                     "Goudies 2 Raws"="Rotorua Raws",                
                                                                                                     "Goudies Raws"="Rotorua Raws",                  
                                                                                                     "Hautu Raws" = "Hautu Raws",                 
                                                                                                     "Matea Raws" = "Matea Raws",                    
                                                                                                     "Minginui Raws"="Minginui Raws",                 
                                                                                                     "Rotoaira Raws"="Rotoaira Raws",                
                                                                                                     "Ruatahuna Raws"="Ruatahuna Raws",                
                                                                                                     "Tahorakuri Raws"= "Tahorakuri Raws",              
                                                                                                     "Taupo Raws"= "Taupo Raws",                  
                                                                                                     "Taupo SYNOP"=  "Taupo SYNOP",                 
                                                                                                     "Tihoi Raws"="Tihoi Raws",                    
                                                                                                     "Chatham Islands Aero SYNOP"= "Chatham Islands Aero SYNOP",
                                                                                                     "Kaiwhata Raws"="Kaiwhata Raws",                 
                                                                                                     "Waitangi Raws" = "Waitangi Raws",              
                                                                                                     "Fernside Raws" =   "Fernside Raws",              
                                                                                                     "Gisborne Raws" =  "Gisborne Raws",                
                                                                                                     "Gisborne SYNOP" =  "Gisborne SYNOP",            
                                                                                                     "Hicks Bay SYNOP" = "Hicks Bay SYNOP",            
                                                                                                     "Matawai Raws" = "Matawai Raws",                
                                                                                                     "Poroporo Raws" =   "Poroporo Raws",               
                                                                                                     "Pouawa Raws" = "Pouawa Raws",                  
                                                                                                     "Raparapaririki Raws" = "Raparapaririki Raws",           
                                                                                                     "Wharekahika Raws" = "Wharekahika Raws",         
                                                                                                     "Wharekopae Raws" = "Wharekopae Raws",              
                                                                                                     "Gwavas Raws" = "Gwavas Raws",                  
                                                                                                     "Ongaonga Raws" = "Ongaonga Raws",                 
                                                                                                     "Porangahau Raws" = "Porangahau Raws",              
                                                                                                     "Waipukurau Raws" = "Waipukurau Raws",               
                                                                                                     "Bridge Pa Raws" = "Bridge Pa Raws",                
                                                                                                     "Crownthorpe Raws" =  "Crownthorpe Raws",            
                                                                                                     "Kaiwaka Raws" = "Kaiwaka Raws",                   
                                                                                                     "Napier Aero SYNOP" = "Napier Aero SYNOP",             
                                                                                                     "Napier Raws" = "Napier Raws",                  
                                                                                                     "Te Apiti Road Raws" = "Te Apiti Road Raws",            
                                                                                                     "Te Haroto Raws" = "Te Haroto Raws",                
                                                                                                     "Te Pohue Raws" = "Te Pohue Raws",                
                                                                                                     "Waihau Raws" =  "Waihau Raws",                 
                                                                                                     "Cricklewood Raws" =   "Cricklewood Raws",            
                                                                                                     "Kaitawa Raws"= "Kaitawa Raws",                 
                                                                                                     "Mahia Aws" = "Mahia Aws",                     
                                                                                                     "Mahia Raws" = "Mahia Raws",                    
                                                                                                     "Tuai Raws" = "Tuai Raws",                   
                                                                                                     "Tuwharetoi Raws"= "Tuwharetoi Raws",               
                                                                                                     "Wairoa Raws" = "Wairoa Raws",                   
                                                                                                     "Wharerata Raws" = "Wharerata Raws",               
                                                                                                     "Aupouri Peninsula Raws" =  "Aupouri Peninsula Raws",       
                                                                                                     "Hokianga Raws" =  "Hokianga Raws",               
                                                                                                     "Kaeo Raws" = "Kaeo Raws",                   
                                                                                                     "Kaikohe Aws" = "Kaikohe Aws",                   
                                                                                                     "Kaikohe Raws" =  "Kaikohe Raws",                
                                                                                                     "Towai Raws" =  "Towai Raws",                 
                                                                                                     "Waitangi Forest Raws" =  "Waitangi Forest Raws",         
                                                                                                     "Dargaville Raws" =   "Dargaville Raws",            
                                                                                                     "Mangakahia Raws" = "Mangakahia Raws",              
                                                                                                     "Opouteke Raws" =  "Opouteke Raws",                
                                                                                                     "Pouto Raws" =  "Pouto Raws",                   
                                                                                                     "Whangarei Aero Aws" = "Whangarei Aero Aws",           
                                                                                                     "Whangarei Raws" = "Whangarei Raws",              
                                                                                                     "Eltham Raws"  = "Eltham Raws" ,                 
                                                                                                     "Hawera Aws" = "Hawera Aws",                   
                                                                                                     "Marco Raws" =  "Marco Raws" ,                  
                                                                                                     "New Plymouth SYNOP" =  "New Plymouth SYNOP",           
                                                                                                     "Ngamatapouri Raws" =  "Ngamatapouri Raws",           
                                                                                                     "Okato Raws" = "Okato Raws",                    
                                                                                                     "Opunake Raws" = "Opunake Raws",                  
                                                                                                     "Tikorangi Raws" = "Tikorangi Raws",               
                                                                                                     "Waverly Raws" = "Waverly Raws",                  
                                                                                                     "Whareroa Raws" =  "Whareroa Raws",                
                                                                                                     "Paeroa Aws" =  "Paeroa Aws",                  
                                                                                                     "Paeroa Raws" =  "Paeroa Raws",                  
                                                                                                     "Te Akau Raws" = "Te Akau Raws",                  
                                                                                                     "Waeranga Raws" = "Waeranga Raws",               
                                                                                                     "Waihi Gold Raws" = "Waihi Gold Raws",               
                                                                                                     "Waihi Raws" = "Waihi Raws",                    
                                                                                                     "Waikawau Bay Raws" = "Waikawau Bay Raws",            
                                                                                                     "Whangamata Raws" = "Whangamata Raws",
                                                                                                     "Athol Raws" =  "Athol Raws",                  
                                                                                                     "Hamilton Aws" = "Hamilton Aws",                 
                                                                                                     "Hamilton Raws" =  "Hamilton Raws",                
                                                                                                     "Piopio Raws" = "Piopio Raws",                   
                                                                                                     "Port Taharoa Aws" ="Port Taharoa Aws",              
                                                                                                     "Taharoa Raws" = "Taharoa Raws",                  
                                                                                                     "Waitomo Raws" = "Waitomo Raws",                   
                                                                                                     "Castlepoint SYNOP" = "Castlepoint SYNOP",            
                                                                                                     "Crofoot Raws" = "Crofoot Raws",                  
                                                                                                     "Holdsworth Station Raws" = "Holdsworth Station Raws",       
                                                                                                     "Homebush Raws" = "Homebush Raws",                
                                                                                                     "Masterton Aero Aws" = "Masterton Aero Aws",             
                                                                                                     "Ngaumu Forest 2 Raws" = "Ngaumu Forest 2 Raws",          
                                                                                                     "Ngaumu Forest Raws" = "Ngaumu Forest Raws",           
                                                                                                     "Tinui Raws" =  "Tinui Raws",                   
                                                                                                     "Featherston Raws" =  "Featherston Raws",             
                                                                                                     "Haurangi Raws" =  "Haurangi Raws",               
                                                                                                     "Ngawi Aws" ="Ngawi Aws",                      
                                                                                                     "Palliser Raws" = "Palliser Raws",                  
                                                                                                     "Stony Creek Raws" =  "Stony Creek Raws",           
                                                                                                     "Te Muna Raws" = "Te Muna Raws",                  
                                                                                                     "Levin Aws" = "Levin Aws",                     
                                                                                                     "Waitarere Forest Raws" = "Waitarere Forest Raws",        
                                                                                                     "Feilding Raws" = "Feilding Raws",                  
                                                                                                     "Hunterville Raws" =  "Hunterville Raws",             
                                                                                                     "Tapuae Raws" = "Tapuae Raws",                  
                                                                                                     "Ngahere Park Raw" = "Ngahere Park Raws",            
                                                                                                     "Palmerston North SYNOP" = "Palmerston North SYNOP",        
                                                                                                     "Ngamatea Raws" =  "Ngamatea Raws",               
                                                                                                     "Raumai Raws" = "Raumai Raws",                   
                                                                                                     "Whangaehu Raws" = "Whangaehu Raws",                
                                                                                                     "Desert Road Summit Raws" = "Desert Road Summit Raws",     
                                                                                                     "Kirikau Raws" = "Kirikau Raws",                   
                                                                                                     "National Park Raws" =  "National Park Raws",           
                                                                                                     "Paradise Valley Raws" = "Paradise Valley Raws",         
                                                                                                     "Tarn Track Raws" = "Tarn Track Raws",               
                                                                                                     "Three Kings Raws" = "Three Kings Raws",            
                                                                                                     "Waimarino Forest Raws" = "Waimarino Forest Raws",        
                                                                                                     "Waiouru Airstrip Aws" =  "Waiouru Airstrip Aws",         
                                                                                                     "Westlawn Raws" = "Westlawn Raws",                  
                                                                                                     "Akitio Ews" = "Akitio Ews",                   
                                                                                                     "Alfredton Raws" =  "Alfredton Raws",               
                                                                                                     "Alfredton South Raws" = "Alfredton South Raws",         
                                                                                                     "Dannevirke Ews" =  "Dannevirke Ews",            
                                                                                                     "Pahiatua Ews" = "Pahiatua Ews",                  
                                                                                                     "Waione East Raws" = "Waione East Raws",              
                                                                                                     "Waione Raws" =  "Waione Raws",                 
                                                                                                     "Matarawa Raws" =  "Matarawa Raws",                
                                                                                                     "Ranana Raws" = "Ranana Raws",                   
                                                                                                     "Wanganui Aws" = "Wanganui Aws",                 
                                                                                                     "Wanganui,Spriggens Park Ews" = "Wanganui,Spriggens Park Ews",   
                                                                                                     "Whanganui Raws" =  "Whanganui Raws",               
                                                                                                     "Belmont Raws" = "Belmont Raws",                 
                                                                                                     "Long Gully Raws" = "Long Gully Raws",               
                                                                                                     "Remutaka Forest Park Raws" = "Remutaka Forest Park Raws",   
                                                                                                     "Wellington Aero SYNOP" = "Wellington Aero SYNOP",        
                                                                                                     "Paraparaumu Aero SYNOP" = "Paraparaumu Aero SYNOP",        
                                                                                                     "Porirua, Elsdon Park Aws" =  "Porirua, Elsdon Park Aws",     
                                                                                                     "Te Horo Raws" = "Te Horo Raws",                 
                                                                                                     "Titahi Bay Raws" = "Titahi Bay Raws",               
                                                                                                     "Bottle Lake Forest Raws" =  "Bottle Lake Forest Raws",      
                                                                                                     "Diamond Harbour Raws" = "Diamond Harbour Raws",         
                                                                                                     "Early Valley Raws" = "Early Valley Raws",             
                                                                                                     "Godley Head Raws" =  "Godley Head Raws",             
                                                                                                     "Le Bons Bay Aws" =   "Le Bons Bay Aws",            
                                                                                                     "Panama Road Raws" = "Panama Road Raws",             
                                                                                                     "Salt Water Creek Raws" =  "Salt Water Creek Raws",        
                                                                                                     "Southbridge Raws" = "Southbridge Raws",             
                                                                                                     "Te Oka Raws" =  "Te Oka Raws",                  
                                                                                                     "Cass Raws" = "Cass Raws",                     
                                                                                                     "Hanmer Forest Ews" = "Hanmer Forest Ews",            
                                                                                                     "Lees Valley Raws" = "Lees Valley Raws" ,               
                                                                                                     "Oxford 2 Raws" = "Oxford 2 Raws",                 
                                                                                                     "Oxford Raws" =  "Oxford Raws",                
                                                                                                     "Snowdon Raws" = "Snowdon Raws",                   
                                                                                                     "Ashley Raws" = "Ashley Raws",                   
                                                                                                     "Balmoral Raws" = "Balmoral Raws",                 
                                                                                                     "Cheviot Raws" = "Cheviot Raws",                  
                                                                                                     "Omihi Raws" =  "Omihi Raws",                  
                                                                                                     "Albury Raws" = "Albury Raws",                  
                                                                                                     "Ashburton Plains Raws" = "Ashburton Plains Raws",         
                                                                                                     "Burnham Raws" = "Burnham Raws",                  
                                                                                                     "Christchurch Aero SYNOP" = "Christchurch Aero SYNOP",      
                                                                                                     "Forest Plains Raws" = "Forest Plains Raws",            
                                                                                                     "Leeston Raws" = "Leeston Raws",                 
                                                                                                     "McLeans Raws" = "McLeans Raws",                 
                                                                                                     "Motukarara Raws" = "Motukarara Raws",               
                                                                                                     "West Melton Raws" =  "West Melton Raws",             
                                                                                                     "Cape Campbell SYNOP" = "Cape Campbell SYNOP",          
                                                                                                     "Kaikoura SYNOP" = "Kaikoura SYNOP",                
                                                                                                     "Glenveigh Kaikoura Raws" = "Glenveigh Kaikoura Raws",      
                                                                                                     "Landsdowne Raws" =  "Landsdowne Raws",            
                                                                                                     "Mid Awatere Valley Raws" = "Mid Awatere Valley Raws",       
                                                                                                     "Molesworth Raws" = "Molesworth Raws",               
                                                                                                     "Onamalutu Raws" = "Onamalutu Raws",               
                                                                                                     "Pudding Hill Raws" = "Pudding Hill Raws",             
                                                                                                     "Tor Darroch Raws" =  "Tor Darroch Raws",             
                                                                                                     "Upper Clarence Raws" = "Upper Clarence Raws",          
                                                                                                     "Ward Raws" = "Ward Raws" ,                   
                                                                                                     "Awatere Valley, Dashwood Raws" = "Awatere Valley, Dashwood Raws",
                                                                                                     "Blenheim Aero Aws" = "Blenheim Aero Aws",           
                                                                                                     "Lower Wairau Raws" = "Lower Wairau Raws",            
                                                                                                     "Kenepuru Head Raws" =  "Kenepuru Head Raws",           
                                                                                                     "Koromiko Raws" = "Koromiko Raws",                
                                                                                                     "Opua Bay Raws" = "Opua Bay Raws",                 
                                                                                                     "Rai Valley Raws" = "Rai Valley Raws",               
                                                                                                     "Timaru Aero SYNOP" = "Timaru Aero SYNOP",             
                                                                                                     "Timaru Coastal Raws" =  "Timaru Coastal Raws",          
                                                                                                     "Waimate Coastal Raws" =  "Waimate Coastal Raws",         
                                                                                                     "Cattle Creek Raws" = "Cattle Creek Raws",            
                                                                                                     "Clayton Raws" = "Clayton Raws",                  
                                                                                                     "Geraldine Forest Raws" = "Geraldine Forest Raws",         
                                                                                                     "Glenaan Station Raws" =  "Glenaan Station Raws",       
                                                                                                     "Glentanner Raws" = "Glentanner Raws",               
                                                                                                     "Hakatere Raws" = "Hakatere Raws",                 
                                                                                                     "Mount Cook Ews" = "Mount Cook Ews",               
                                                                                                     "Mount Somers Raws" = "Mount Somers Raws",             
                                                                                                     "Pukaki Aero Raws" =  "Pukaki Aero Raws",             
                                                                                                     "Tekapo Raws" = "Tekapo Raws",                  
                                                                                                     "Waihaorunga Raws" = "Waihaorunga Raws",               
                                                                                                     "Ashburton Aero Raws" = "Ashburton Aero Raws",           
                                                                                                     "Ashburton Plains 2 Raws" = "Ashburton Plains 2 Raws",      
                                                                                                     "Cannington Raws" = "Cannington Raws",               
                                                                                                     "Waimate Forest Raws" = "Waimate Forest Raws",           
                                                                                                     "Hira Raws" = "Hira Raws",                    
                                                                                                     "Nelson Aws" = "Nelson Aws",                    
                                                                                                     "Nelson Raws" = "Nelson Raws",                   
                                                                                                     "Takaka Aerodrome Raws" = "Takaka Aerodrome Raws",         
                                                                                                     "Big Pokororo 2 Raws" =  "Big Pokororo 2 Raws",          
                                                                                                     "Big Pokororo Raws" = "Big Pokororo Raws",             
                                                                                                     "Dovedale Raws" = "Dovedale Raws",                
                                                                                                     "Murchison Raws" = "Murchison Raws",                
                                                                                                     "St Arnaud Raws" =  "St Arnaud Raws",               
                                                                                                     "Western Boundary Raws" = "Western Boundary Raws",        
                                                                                                     "Glenledi Raws" = "Glenledi Raws" ,                 
                                                                                                     "Nugget Point Aws" = "Nugget Point Aws",              
                                                                                                     "Tapanui Raws" = "Tapanui Raws",                 
                                                                                                     "Toko Mouth Raws" =  "Toko Mouth Raws",              
                                                                                                     "Waipahi Raws" =  "Waipahi Raws",                 
                                                                                                     "Bucklands Raws" =  "Bucklands Raws",              
                                                                                                     "Dunedin Aero SYNOP" = "Dunedin Aero SYNOP",            
                                                                                                     "Dunedin Raws" =  "Dunedin Raws",                 
                                                                                                     "Traquair Raws" = "Traquair Raws",                
                                                                                                     "Butchers Dam Raws" = "Butchers Dam Raws",             
                                                                                                     "Clyde 2 Ews" = "Clyde 2 Ews",                   
                                                                                                     "Cromwell Ews" = "Cromwell Ews",                 
                                                                                                     "Dansey Pass Raws" = "Dansey Pass Raws",              
                                                                                                     "Glendhu Raws" = "Glendhu Raws",                  
                                                                                                     "Lauder Ews" = "Lauder Ews",                   
                                                                                                     "Millers Flat Raws" =  "Millers Flat Raws",            
                                                                                                     "Naseby Forest Raws" = "Naseby Forest Raws",           
                                                                                                     "Otematata Raws" =  "Otematata Raws",              
                                                                                                     "Ranfurly Ews" = "Ranfurly Ews",                  
                                                                                                     "Rock And Pillar Raws" =  "Rock And Pillar Raws",         
                                                                                                     "Hawea Flat Raws" = "Hawea Flat Raws",              
                                                                                                     "Queenstown Aero Raws" =  "Queenstown Aero Raws",         
                                                                                                     "Queenstown Aero SYNOP" =  "Queenstown Aero SYNOP",        
                                                                                                     "Wanaka Aero Aws" = "Wanaka Aero Aws",              
                                                                                                     "Herbert Raws" =  "Herbert Raws",                
                                                                                                     "Macrae's Raws" = "Macrae's Raws",                 
                                                                                                     "Oamaru Airport Aws" =  "Oamaru Airport Aws",          
                                                                                                     "Oamaru Aws" = "Oamaru Aws",                   
                                                                                                     "Oamaru North Raws" = "Oamaru North Raws",             
                                                                                                     "Tara Hills Aws" = "Tara Hills Aws",               
                                                                                                     "Windsor Ews" = "Windsor Ews",                   
                                                                                                     "Barnhill Raws" = "Barnhill Raws",                 
                                                                                                     "Garston Raws" = "Garston Raws",                 
                                                                                                     "Invercargill Aero SYNOP" =  "Invercargill Aero SYNOP",     
                                                                                                     "Lumsden Aws" = "Lumsden Aws",                   
                                                                                                     "Otama Raws" = "Otama Raws",                   
                                                                                                     "Tanner Road Raws" = "Tanner Road Raws",               
                                                                                                     "Tisbury Raws" = "Tisbury Raws",                  
                                                                                                     "Tuatapere Raws" = "Tuatapere Raws",               
                                                                                                     "Wreys Bush Raws" =  "Wreys Bush Raws",              
                                                                                                     "Edendale Raws"  =  "Edendale Raws",                
                                                                                                     "Gore Aws"  = "Gore Aws",                   
                                                                                                     "Milford Sound Raws" = "Milford Sound Raws",            
                                                                                                     "Slopedown Raws" =  "Slopedown Raws",               
                                                                                                     "South West Cape SYNOP" = "South West Cape SYNOP",        
                                                                                                     "Stewart Island Raws" = "Stewart Island Raws",           
                                                                                                     "Blackmount Raws" =  "Blackmount Raws",               
                                                                                                     "Manapouri Aero Aws" = "Manapouri Aero Aws",           
                                                                                                     "Wilderness Raws" =  "Wilderness Raws",              
                                                                                                     "Charleston Raws" =  "Charleston Raws",              
                                                                                                     "Haast Junction Raws" = "Haast Junction Raws",          
                                                                                                     "Haast SYNOP" =  "Haast SYNOP",                 
                                                                                                     "Hokitika Raws" = "Hokitika Raws",                 
                                                                                                     "Hokitika SYNOP" = "Hokitika SYNOP",               
                                                                                                     "Karamea Raws" =  "Karamea Raws",                  
                                                                                                     "Westport Aero Aws" = "Westport Aero Aws",             
                                                                                                     "Lake Brunner Raws" = "Lake Brunner Raws",            
                                                                                                     "Maruia Raws" = "Maruia Raws",                   
                                                                                                     "Nelson Creek Raws" = "Nelson Creek Raws",              
                                                                                                     "Reefton Ews" = "Reefton Ews",                   
                                                                                                     "Aniseed Valley Raws" = "Aniseed Valley Raws",           
                                                                                                     "Broadwood Raws" = "Broadwood Raws",                
                                                                                                     "Manaia Raws" = "Manaia Raws",                  
                                                                                                     "Parapara Raws" = "Parapara Raws",                 
                                                                                                     "Waitarere Raws" = "Waitarere Raws",                
                                                                                                     "Whangamata 2 Raws" = "Whangamata 2 Raws"
                                  ), selected = "Great Barrier Island Raws"),
                                  
                                  withSpinner(plotOutput(outputId = "Mosaic"),type = 5, color = "#FFA500", size = 1)
                                  
                                  
                         ),
                       
                                  
                        tabPanel("Region Plots",
                                 
                                 
                                 sliderInput(inputId = "newcomp", label = "Select Year", min = 1970, max = 2019, value = 2007),
                                 selectInput(inputId = "indexxx", label ="Index:", choices = list("BUI" = "BUI",
                                                                                                 "CDSR" = "CDSR",
                                                                                                 "DC" = "DC"
                                 ), selected = "BUI"),
                                 
                                 selectInput(inputId = "region", label ="Region:", choices = list("Auckland" = "Auckland",
                                                                                                  "Bay of Plenty" = "Bay of Plenty",
                                                                                                  "Central NI" = "Central NI",
                                                                                                  "Chatham Island" ="Chatham Island" ,
                                                                                                  "Gisborne"="Gisborne",
                                                                                                  "Hawkes Bay"="Hawkes Bay",
                                                                                                  "Northland"="Northland",
                                                                                                  "Taranaki"= "Taranaki",
                                                                                                  "Waikato"="Waikato",
                                                                                                  "Wairarapa" ="Wairarapa" ,
                                                                                                  "Wanganui-Manawatu"="Wanganui-Manawatu",
                                                                                                  "Wellington"= "Wellington",
                                                                                                  "Canterbury" ="Canterbury" ,
                                                                                                  "Marlborough" = "Marlborough" ,
                                                                                                  "Mid-South Canterbury"= "Mid-South Canterbury",
                                                                                                  "Nelson"= "Nelson",
                                                                                                  "Otago"="Otago",
                                                                                                  "Southland"="Southland",
                                                                                                  "West Coast" ="West Coast" ,
                                                                                                  "unknown region"  = "unknown region"
                                                                                                  
                                                                                                  
                                                                                                  
                                                                                                  
                                                                                                  
                                                                                                  
                                 ), selected = "Auckland"),
                                 
                                 
                                 mainPanel(uiOutput("plots"))
                                 # mainPanel(
                                 #   # This is the dynamic UI for the plots
                                 #uiOutput("plots")
                                 # )
                                 #  
                         )
                         # how to plot station wise, the station names are big, dataset doesn't contain station codes

                       
              )
              )
              )
              )
              )
                      
                       